package eu.solven.matmul.docs.generate;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import eu.solven.matmul.NonCubicBilinearAlgorithm;
import eu.solven.matmul.algebra.Field;
import eu.solven.matmul.catalog.FieldAwareLookup;
import eu.solven.matmul.catalog.SchemeIO;
import eu.solven.matmul.isotropy.RecombinationMultisetOrbit;

/**
 * Generate {@code references/recomb-multisets-base-{base}.md} — the
 * <b>dominance frontier</b> of a base scheme's recombination-multiset variety.
 *
 * <p>The full canonical set of recombination multisets of a base explodes once
 * an axis has ≥3 parts ({@code ⟨2,2,3⟩} → ~12k, {@code ⟨3,3,3⟩} → intractable).
 * But matmul rank is monotone, so the recombination cost {@code Σ R(sub-shapeₖ)}
 * is order-preserving under sub-shape dominance: only the
 * {@link RecombinationMultisetOrbit.Result#dominanceFrontier() dominance frontier}
 * can ever be rank-optimal. This report lists <i>only</i> that frontier — the
 * meaningful, tractable study (e.g. {@code ⟨2,2,3⟩}: 12,217 → ~40).</p>
 *
 * <p>Run: {@code mvn -q -ntp exec:java
 * -Dexec.mainClass=eu.solven.matmul.docs.generate.GenerateBaseMultisetFrontier
 * -Dexec.args="--base=2x2x3 --bound=2"}</p>
 */
public final class GenerateBaseMultisetFrontier {
	private GenerateBaseMultisetFrontier() {}

	public static void main(String[] args) throws IOException {
		String baseShape = arg(args, "--base", "2x2x3");
		int bound = Integer.parseInt(arg(args, "--bound", "2"));
		String[] dims = baseShape.split("x");
		int n = Integer.parseInt(dims[0]), m = Integer.parseInt(dims[1]), p = Integer.parseInt(dims[2]);

		FieldAwareLookup lk = new FieldAwareLookup(Field.Q);
		Path basePath = pickIntegerBase(lk, n, m, p);
		if (basePath == null) {
			throw new IllegalStateException("no integer base at " + baseShape);
		}
		NonCubicBilinearAlgorithm base = SchemeIO.read(basePath.toFile());
		String baseName = basePath.getFileName().toString();

		// Enumerate at bound-1 and the requested bound, so we can report whether the
		// FRONTIER stabilises even when the full canonical set is still growing.
		var lo = RecombinationMultisetOrbit.enumerate(base, Math.max(1, bound - 1));
		var hi = RecombinationMultisetOrbit.enumerate(base, bound);
		List<String> frontierLo = lo.dominanceFrontier();
		List<String> frontier = hi.dominanceFrontier();       // canonical (S-quotiented) level
		List<String> ncFrontier = hi.nonCanonicalFrontier();  // axis-tagged level
		int ncCount = hi.nonCanonicalCount();
		boolean frontierStable = frontierLo.size() == frontier.size();

		int[] maxIdx = { n - 1, m - 1, p - 1 };

		StringBuilder md = new StringBuilder();
		md.append("# Recombination multisets — base ⟨").append(n).append(',').append(m).append(',').append(p)
				.append("⟩ — dominance frontier\n\n");
		md.append("*Generated by `GenerateBaseMultisetFrontier --base=").append(baseShape)
				.append(" --bound=").append(bound).append("`. Do not edit by hand.*\n\n");
		md.append("Base scheme: `").append(baseName).append("` (⟨").append(base.n).append(',').append(base.m)
				.append(',').append(base.p).append("⟩ r=").append(base.r).append(", integer factors, Q).\n\n");
		md.append("> **The frontier is specific to this GL-representative.** `enumerate` sweeps the\n");
		md.append("> `GL×GL×GL` isotropy orbit only — *not* the transpose/duality symmetries that make all\n");
		md.append("> rank-`r` schemes of a shape equivalent. So a different rank-`r` base of the same shape can\n");
		md.append("> yield a different multiset variety and a different frontier (e.g. Strassen ⟨2,2,2⟩ → 8,\n");
		md.append("> Winograd/AlphaTensor-Z ⟨2,2,2⟩ → 7). Re-run with the base you intend to recombine.\n\n");

		md.append("## Why a frontier (not the full set)\n\n");
		md.append("A recombination sends each of the base's `r` products to a sub-matmul whose per-axis size is the\n");
		md.append("block it lands on (**index 0 = largest block = most expensive**, under *any* allocation). The total\n");
		md.append("rank is `Σ R(sub-shapeₖ)`, and matmul rank is **monotone** (a bigger sub-multiply never costs less —\n");
		md.append("pad the small one in). So if multiset *A* matches *B* product-by-product with every *A*-block ≤ the\n");
		md.append("paired *B*-block, then `cost(A) ≤ cost(B)` for **every** base recursion, and *B* can never be optimal.\n");
		md.append("Keeping only the **dominance frontier** (the non-dominated antichain) is therefore *lossless for the\n");
		md.append("rank minimum* and *allocation/base-independent*. The frontier is an antichain — it cannot collapse to\n");
		md.append("one point because the three axes are coupled (a product is one corner-type across all axes at once),\n");
		md.append("so several incomparable trade-offs survive; the minimum at any concrete allocation is one of them.\n\n");

		md.append("## Summary\n\n");
		md.append("Two quotient levels. **Canonical** = multisets up to the base's axis symmetry");
		md.append(" (the right level for symmetric / axis-permuted allocations; dominance is");
		md.append(" axis-permutation aware). **Axis-tagged** = no quotient (lossless for asymmetric");
		md.append(" allocations too, where axis identity matters). Both frontiers are seed-independent.\n\n");
		md.append("| metric | canonical | axis-tagged |\n|---|---|---|\n");
		md.append("| per-axis pattern counts (bound ").append(bound).append(") | `")
				.append(java.util.Arrays.toString(hi.perAxisPatternCounts)).append("` | — |\n");
		md.append("| multisets (bound ").append(bound).append(") | ")
				.append(String.format("%,d", hi.canonicalMultisets.size())).append(" | ")
				.append(String.format("%,d", ncCount)).append(" |\n");
		md.append("| **dominance frontier** | **").append(frontier.size()).append("** | **")
				.append(ncFrontier.size()).append("** |\n");
		md.append("| pruning ratio | ")
				.append(String.format("%.1f×", hi.canonicalMultisets.size() / (double) Math.max(1, frontier.size())))
				.append(" | ").append(String.format("%.1f×", ncCount / (double) Math.max(1, ncFrontier.size())))
				.append(" |\n");
		md.append("| frontier at bound ").append(Math.max(1, bound - 1)).append(" | ").append(frontierLo.size())
				.append(frontierStable ? " (stable)" : " (**still growing** — treat as a bound)")
				.append(" | — |\n\n");

		if (!frontierStable) {
			md.append("> ⚠️ The frontier size changed from bound ").append(Math.max(1, bound - 1)).append(" to ")
					.append(bound).append("; for ≥3-part axes the orbit sweep is not certified complete, so this\n")
					.append("> frontier is an **upper bound** on the candidate set, not a proven-complete enumeration.\n\n");
		}

		md.append("## Canonical frontier multisets\n\n");
		md.append("Symbolic in the block sizes (`x₁` = largest part of axis x, `x₂` next, …). Sorted by total\n");
		md.append("\"smallness\" (cheapest sub-shape mass first). `pure-big` = products on the all-largest block;\n");
		md.append("`pure-small` = products on the all-smallest block; `mixed` = the rest.\n\n");
		md.append("| # | multiset | pure-big | mixed | pure-small |\n|---|---|---|---|---|\n");
		int row = 1;
		for (String key : frontier) {
			int[][] shapes = hi.representativeShapes.get(key);
			int big = 0, small = 0, mixed = 0;
			for (int[] t : shapes) {
				boolean allBig = t[0] == 0 && t[1] == 0 && t[2] == 0;
				boolean allSmall = t[0] == maxIdx[0] && t[1] == maxIdx[1] && t[2] == maxIdx[2];
				if (allBig) {
					big++;
				} else if (allSmall) {
					small++;
				} else {
					mixed++;
				}
			}
			md.append("| ").append(row++).append(" | ")
					.append(RecombinationMultisetOrbit.prettySymbolic(key, "n", "m", "p")).append(" | ")
					.append(big).append(" | ").append(mixed).append(" | ").append(small).append(" |\n");
		}
		md.append('\n');

		Path out = Path.of("references", "recomb-multisets-base-" + baseShape + ".md");
		Files.createDirectories(out.getParent());
		Files.writeString(out, md.toString());
		System.out.printf("Wrote %s : %,d canonical → %d frontier (pruning %.1f×)%n",
				out, hi.canonicalMultisets.size(), frontier.size(),
				hi.canonicalMultisets.size() / (double) Math.max(1, frontier.size()));
	}

	/** First integer-factor base at the shape (prefers a recognised NC source token).
	 *  Returns the Path so the report can record the exact GL-representative — the
	 *  frontier is base-dependent (enumerate sweeps GL³ only, not transpose duality). */
	private static Path pickIntegerBase(FieldAwareLookup lk, int n, int m, int p) {
		Path fallback = null;
		for (var path : lk.findFiles(n, m, p)) {
			NonCubicBilinearAlgorithm x;
			try {
				x = SchemeIO.read(path.toFile());
			} catch (Exception e) {
				continue;
			}
			if (x.n != n || x.m != m || x.p != p || !isInteger(x)) {
				continue;
			}
			String fn = path.getFileName().toString();
			if (fn.contains("alphatensor_Z") || fn.contains("strassen") || fn.contains("laderman")) {
				return path;
			}
			if (fallback == null) {
				fallback = path;
			}
		}
		return fallback;
	}

	private static boolean isInteger(NonCubicBilinearAlgorithm x) {
		for (double[][] M : new double[][][] { x.denseU(), x.denseV(), x.denseW() }) {
			for (double[] row : M) {
				for (double v : row) {
					if (Math.abs(v - Math.rint(v)) > 1e-9) {
						return false;
					}
				}
			}
		}
		return true;
	}

	private static String arg(String[] args, String key, String def) {
		for (String a : args) {
			if (a.startsWith(key + "=")) {
				return a.substring(key.length() + 1);
			}
		}
		return def;
	}
}
