package eu.solven.matmul.docs.generate;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.OptionalLong;

import eu.solven.matmul.papers.ta.TrilinearAggregation;
import eu.solven.matmul.papers.ta.TrilinearAggregations;
import lombok.extern.slf4j.Slf4j;

/**
 * Emits the trilinear-aggregation family comparison for the paper: every TA
 * member's cubic rank {@code R(⟨N,N,N⟩)} over {@code N = 1..64}, as
 *
 * <ul>
 *   <li>{@code paper/generated/ta-family-ranks.csv} — raw ranks per method +
 *       the family best and the winning method (blank cells = method N/A at that N);</li>
 *   <li>{@code paper/generated/ta-family-ranks.tex} — a {@code pgfplots} figure of the
 *       NORMALISED leading constant {@code 3·R(N)/N³} (→ 1 asymptotically; lower is
 *       better) per method, so the crossovers — i.e. which method improves over
 *       which range — are visible. {@code \input}-able from the paper.</li>
 * </ul>
 *
 * <p>Single source of truth: {@link TrilinearAggregations}. Re-run to refresh.</p>
 *
 * <pre>mvn -q exec:java -Dexec.mainClass=eu.solven.matmul.docs.generate.GenerateTaFamilyComparison</pre>
 */
@Slf4j
public final class GenerateTaFamilyComparison {

	private static final int MAX_N = 64;
	private static final Path OUT_DIR = Path.of("paper/generated");
	private static final Path CSV = OUT_DIR.resolve("ta-family-ranks.csv");
	private static final Path TEX = OUT_DIR.resolve("ta-family-ranks.tex");

	private GenerateTaFamilyComparison() {}

	// pgfplots styling per member (colour + mark), in registry order.
	private record Style(String tag, String legend, String colour, String mark) {}

	private static final List<Style> STYLES = List.of(
			new Style("TA_pan", "TA\\_pan (Pan 1980)", "gray", "x"),
			new Style("TA_dis", "TA\\_dis (Islam/DIS09)", "blue", "*"),
			new Style("TA_hs", "TA\\_hs (Hadas--Schwartz 1982)", "teal", "triangle*"),
			new Style("TA_sz", "TA\\_sz (Schwartz--Zwecher 2025)", "orange", "square*"),
			new Style("TA_lita", "TA\\_lita (KGP 2026)", "red", "diamond*"));

	public static void main(String[] args) throws IOException {
		Files.createDirectories(OUT_DIR);
		List<TrilinearAggregation> members = TrilinearAggregations.all();

		try (PrintWriter csv = new PrintWriter(Files.newBufferedWriter(CSV))) {
			csv.print("N");
			for (TrilinearAggregation m : members) {
				csv.print("," + m.tag());
			}
			csv.println(",best,best_method");
			for (int n = 1; n <= MAX_N; n++) {
				csv.print(n);
				for (TrilinearAggregation m : members) {
					OptionalLong r = m.cubicRank(n);
					csv.print("," + (r.isPresent() ? Long.toString(r.getAsLong()) : ""));
				}
				var best = TrilinearAggregations.best(n);
				csv.print("," + (best.map(b -> Long.toString(b.rank())).orElse("")));
				csv.println("," + (best.map(b -> b.method().tag()).orElse("")));
			}
		}

		try (PrintWriter tex = new PrintWriter(Files.newBufferedWriter(TEX))) {
			tex.println("% Generated by GenerateTaFamilyComparison — do not edit by hand.");
			tex.println("% Trilinear-aggregation family: normalised leading constant 3*R(N)/N^3 vs N.");
			tex.println("\\begin{figure}[t]");
			tex.println("  \\centering");
			tex.println("  \\begin{tikzpicture}");
			tex.println("    \\begin{axis}[");
			tex.println("        width=\\linewidth, height=6.5cm,");
			tex.println("        xlabel={cube side $N$}, ylabel={$3\\,R(\\langle N,N,N\\rangle)/N^3$},");
			tex.println("        xmin=1, xmax=" + MAX_N + ",");
			tex.println("        legend pos=north east, legend cell align=left,");
			tex.println("        grid=both, major grid style={black!10}, minor grid style={black!5},");
			tex.println("        title={Trilinear-aggregation methods: normalised cubic constant (lower is better)}]");
			for (Style s : STYLES) {
				TrilinearAggregation m = byTag(members, s.tag());
				StringBuilder coords = new StringBuilder();
				for (int n = 2; n <= MAX_N; n++) {
					OptionalLong r = m.cubicRank(n);
					if (r.isEmpty()) {
						continue;
					}
					double y = 3.0 * r.getAsLong() / ((double) n * n * n);
					coords.append(String.format(Locale.ROOT, "(%d,%.4f) ", n, y));
				}
				tex.println("      \\addplot[" + s.colour() + ", mark=" + s.mark()
						+ ", mark size=1.2pt, thick] coordinates {" + coords.toString().trim() + "};");
				tex.println("      \\addlegendentry{" + s.legend() + "}");
			}
			tex.println("    \\end{axis}");
			tex.println("  \\end{tikzpicture}");
			tex.println("  \\caption{Each trilinear-aggregation method gives an alternative rank for "
					+ "$\\langle N,N,N\\rangle$ over its own domain (TA\\_pan/TA\\_hs/TA\\_sz are even only, "
					+ "TA\\_hs/TA\\_sz exclude the $N{=}16$ pole, TA\\_lita requires $N\\ge 19$). Plotted is the "
					+ "normalised leading constant $3R/N^3$; all converge to $1$, and the crossovers show which "
					+ "method is tightest over which range --- TA\\_lita (KGP 2026) dominates for odd $N\\ge 19$ "
					+ "and large even $N$, while TA\\_dis still wins at e.g.\\ $N{=}22$.}");
			tex.println("  \\label{fig:ta-family-ranks}");
			tex.println("\\end{figure}");
		}

		log.info("Wrote {} and {} (N=1..{})", CSV, TEX, MAX_N);
	}

	private static TrilinearAggregation byTag(List<TrilinearAggregation> members, String tag) {
		return members.stream().filter(m -> m.tag().equals(tag)).findFirst().orElseThrow();
	}
}
